using System;
using System.Collections;

namespace System.Data.Odbc
{
	/// <summary>Collects all errors generated by the <see cref="T:System.Data.Odbc.OdbcDataAdapter" />. This class cannot be inherited.</summary>
	/// <filterpriority>2</filterpriority>
	// Token: 0x02000297 RID: 663
	[Serializable]
	public sealed class OdbcErrorCollection : ICollection, IEnumerable
	{
		// Token: 0x06001D06 RID: 7430 RVA: 0x0008E95A File Offset: 0x0008CB5A
		internal OdbcErrorCollection()
		{
		}

		/// <summary>For a description of this member, see <see cref="P:System.Collections.ICollection.SyncRoot" />.</summary>
		/// <returns>An object that can be used to synchronize access to the <see cref="T:System.Collections.ICollection" />.</returns>
		// Token: 0x17000545 RID: 1349
		// (get) Token: 0x06001D07 RID: 7431 RVA: 0x0000565A File Offset: 0x0000385A
		object ICollection.SyncRoot
		{
			get
			{
				return this;
			}
		}

		/// <summary>For a description of this member, see <see cref="P:System.Collections.ICollection.IsSynchronized" />.</summary>
		/// <returns>true if access to the <see cref="T:System.Collections.ICollection" /> is synchronized (thread safe); otherwise, false.</returns>
		// Token: 0x17000546 RID: 1350
		// (get) Token: 0x06001D08 RID: 7432 RVA: 0x00005AE9 File Offset: 0x00003CE9
		bool ICollection.IsSynchronized
		{
			get
			{
				return false;
			}
		}

		/// <summary>Gets the number of errors in the collection.</summary>
		/// <returns>The total number of errors in the collection.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x17000547 RID: 1351
		// (get) Token: 0x06001D09 RID: 7433 RVA: 0x0008E96D File Offset: 0x0008CB6D
		public int Count
		{
			get
			{
				return this._items.Count;
			}
		}

		/// <summary>Gets the error at the specified index.</summary>
		/// <returns>An <see cref="T:System.Data.Odbc.OdbcError" /> that contains the error at the specified index. </returns>
		/// <param name="i">The zero-based index of the error to retrieve. </param>
		/// <filterpriority>2</filterpriority>
		// Token: 0x17000548 RID: 1352
		public OdbcError this[int i]
		{
			get
			{
				return (OdbcError)this._items[i];
			}
		}

		// Token: 0x06001D0B RID: 7435 RVA: 0x0008E98D File Offset: 0x0008CB8D
		internal void Add(OdbcError error)
		{
			this._items.Add(error);
		}

		/// <summary>Copies the elements of the <see cref="T:System.Data.Odbc.OdbcErrorCollection" /> into an array, starting at the specified index within the array.</summary>
		/// <param name="array">The array into which to copy the elements. </param>
		/// <param name="i">The starting index of <paramref name="array" />. </param>
		/// <exception cref="T:System.ArgumentException">The sum of <paramref name="index" /> and the number of elements in the <see cref="T:System.Data.Odbc.OdbcErrorCollection" /> is greater than the length of the array. </exception>
		/// <exception cref="T:System.ArgumentNullException">The <paramref name="array" /> is null. </exception>
		/// <exception cref="T:System.ArgumentOutOfRangeException">The <paramref name="index" /> is not valid for <paramref name="array" />. </exception>
		/// <filterpriority>2</filterpriority>
		// Token: 0x06001D0C RID: 7436 RVA: 0x0008E99C File Offset: 0x0008CB9C
		public void CopyTo(Array array, int i)
		{
			this._items.CopyTo(array, i);
		}

		/// <summary>Copies all the elements of the current <see cref="T:System.Data.Odbc.OdbcErrorCollection" /> to the specified <see cref="T:System.Data.Odbc.OdbcErrorCollection" /> starting at the specified destination index.</summary>
		/// <param name="array">The <see cref="T:System.Data.Odbc.OdbcErrorCollection" /> that is the destination of the elements copied from the current <see cref="T:System.Data.Odbc.OdbcErrorCollection" />.</param>
		/// <param name="i">A 32-bit integer that represents the index in the <see cref="T:System.Data.Odbc.OdbcErrorCollection" /> at which copying starts.</param>
		/// <filterpriority>2</filterpriority>
		// Token: 0x06001D0D RID: 7437 RVA: 0x0008E99C File Offset: 0x0008CB9C
		public void CopyTo(OdbcError[] array, int i)
		{
			this._items.CopyTo(array, i);
		}

		/// <summary>Returns an object that implements the <see cref="T:" /><see cref="System.Collections.IEnumerator" /> interface and that can iterate through the <see cref="T:System.Data.Odbc.OdbcErrorCollection" /> objects in the <see cref="T:System.Data.Odbc.OdbcErrorCollection" />.</summary>
		/// <returns>An object that implements the <see cref="T:" /><see cref="System.Collections.IEnumerator" /> interface and that can iterate through the <see cref="T:System.Data.Odbc.OdbcErrorCollection" /> objects in the <see cref="T:System.Data.Odbc.OdbcErrorCollection" />.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x06001D0E RID: 7438 RVA: 0x0008E9AB File Offset: 0x0008CBAB
		public IEnumerator GetEnumerator()
		{
			return this._items.GetEnumerator();
		}

		// Token: 0x06001D0F RID: 7439 RVA: 0x0008E9B8 File Offset: 0x0008CBB8
		internal void SetSource(string Source)
		{
			foreach (object obj in this._items)
			{
				((OdbcError)obj).SetSource(Source);
			}
		}

		// Token: 0x040015A9 RID: 5545
		private ArrayList _items = new ArrayList();
	}
}
