using System;
using System.Data.Common;
using System.Runtime.Serialization;
using System.Security.Permissions;
using System.Text;
using Unity;

namespace System.Data.Odbc
{
	/// <summary>The exception that is generated when a warning or error is returned by an ODBC data source. This class cannot be inherited.</summary>
	/// <filterpriority>2</filterpriority>
	// Token: 0x02000298 RID: 664
	[Serializable]
	public sealed class OdbcException : DbException
	{
		// Token: 0x06001D10 RID: 7440 RVA: 0x0008EA10 File Offset: 0x0008CC10
		internal static OdbcException CreateException(OdbcErrorCollection errors, ODBC32.RetCode retcode)
		{
			StringBuilder stringBuilder = new StringBuilder();
			foreach (object obj in errors)
			{
				OdbcError odbcError = (OdbcError)obj;
				if (stringBuilder.Length > 0)
				{
					stringBuilder.Append(Environment.NewLine);
				}
				stringBuilder.Append(SR.GetString("{0} [{1}] {2}", new object[]
				{
					ODBC32.RetcodeToString(retcode),
					odbcError.SQLState,
					odbcError.Message
				}));
			}
			return new OdbcException(stringBuilder.ToString(), errors);
		}

		// Token: 0x06001D11 RID: 7441 RVA: 0x0008EAB8 File Offset: 0x0008CCB8
		internal OdbcException(string message, OdbcErrorCollection errors)
		{
			this._odbcErrors = new OdbcErrorCollection();
			base..ctor(message);
			this._odbcErrors = errors;
			base.HResult = -2146232009;
		}

		// Token: 0x06001D12 RID: 7442 RVA: 0x0008EADE File Offset: 0x0008CCDE
		private OdbcException(SerializationInfo si, StreamingContext sc)
		{
			this._odbcErrors = new OdbcErrorCollection();
			base..ctor(si, sc);
			this._odbcErrors = (OdbcErrorCollection)si.GetValue("odbcErrors", typeof(OdbcErrorCollection));
			base.HResult = -2146232009;
		}

		/// <summary>Gets a collection of one or more <see cref="T:System.Data.Odbc.OdbcError" /> objects that give detailed information about exceptions generated by the .NET Framework Data Provider for ODBC.</summary>
		/// <returns>The collected instances of the <see cref="T:System.Data.Odbc.OdbcError" /> class.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x17000549 RID: 1353
		// (get) Token: 0x06001D13 RID: 7443 RVA: 0x0008EB1E File Offset: 0x0008CD1E
		public OdbcErrorCollection Errors
		{
			get
			{
				return this._odbcErrors;
			}
		}

		/// <summary>This member overrides <see cref="M:System.Exception.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)" />.</summary>
		/// <param name="si">The <see cref="T:System.Runtime.Serialization.SerializationInfo" /> that holds the serialized object data about the exception being thrown.</param>
		/// <param name="context">The <see cref="T:System.Runtime.Serialization.StreamingContext" /> that contains contextual information about the source or destination.</param>
		/// <exception cref="T:System.ArgumentNullException">The <paramref name="si" /> parameter is a null reference (Nothing in Visual Basic).</exception>
		/// <filterpriority>2</filterpriority>
		/// <PermissionSet>
		///   <IPermission class="System.Security.Permissions.FileIOPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Unrestricted="true" />
		///   <IPermission class="System.Security.Permissions.SecurityPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Flags="ControlEvidence, SerializationFormatter" />
		/// </PermissionSet>
		// Token: 0x06001D14 RID: 7444 RVA: 0x0008EB26 File Offset: 0x0008CD26
		[SecurityPermission(SecurityAction.LinkDemand, Flags = SecurityPermissionFlag.SerializationFormatter)]
		public override void GetObjectData(SerializationInfo si, StreamingContext context)
		{
			base.GetObjectData(si, context);
			si.AddValue("odbcRetcode", ODBC32.RETCODE.SUCCESS, typeof(ODBC32.RETCODE));
			si.AddValue("odbcErrors", this._odbcErrors, typeof(OdbcErrorCollection));
		}

		/// <summary>Gets the name of the ODBC driver that generated the error.</summary>
		/// <returns>The name of the ODBC driver that generated the error.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x1700054A RID: 1354
		// (get) Token: 0x06001D15 RID: 7445 RVA: 0x0008EB68 File Offset: 0x0008CD68
		public override string Source
		{
			get
			{
				if (0 >= this.Errors.Count)
				{
					return "";
				}
				string source = this.Errors[0].Source;
				if (!string.IsNullOrEmpty(source))
				{
					return source;
				}
				return "";
			}
		}

		// Token: 0x06001D16 RID: 7446 RVA: 0x0000E24C File Offset: 0x0000C44C
		internal OdbcException()
		{
			global::Unity.ThrowStub.ThrowNotSupportedException();
		}

		// Token: 0x040015AA RID: 5546
		private OdbcErrorCollection _odbcErrors;
	}
}
