using System;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Security;
using System.Security.Permissions;
using Pathfinding;
using Pathfinding.Graphs.Navmesh;
using Pathfinding.RVO;
using Pathfinding.Util;
using Unity.Burst;

[assembly: AssemblyVersion("0.0.0.0")]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Polygon.ContainsPoint_000002C6$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Polygon.ClosestPointOnTriangleByRef_000002CD$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Polygon.ClosestPointOnTriangleProjected_000002CF$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(BinaryHeap.Add_000002DF$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(BinaryHeap.Remove_000002E2$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(HeuristicObjective.Calculate_000004C0$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Path.OpenCandidateConnectionBurst_000004FC$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(TriangleMeshNode.InterpolateEdge_00000757$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(TriangleMeshNode.OpenSingleEdgeBurst_0000075C$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(TriangleMeshNode.CalculateBestEdgePosition_0000075D$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(NavmeshCutJobs.CalculateContour_00000875$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Funnel.Calculate_0000090B$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Funnel.FunnelState.PushStart_00000917$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Funnel.FunnelState.ConvertCornerIndicesToPathProjected_00000921$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(PathTracer.ContainsAndProject_00000949$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(PathTracer.EstimateRemainingPath_0000095A$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(PathTracer.RemainingDistanceLowerBound_0000095E$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(BBTree.Build_00000A75$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(BBTree.ProjectionParams.SquaredRectPointDistanceOnPlane_00000A80$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(BBTree.NearbyNodesIterator.MoveNext_00000A87$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(ColliderMeshBuilder2D.GenerateMeshesFromShapes_00000A8F$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(RecastMeshGatherer.CalculateBounds_00000A9B$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(HierarchicalBitset.Iterator.MoveNextBurst_00000CDA$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(MeshUtility.MakeTrianglesClockwise_00000E12$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(RVOObstacleCache.TraceContours_00000EED$BurstDirectCall))]
[assembly: SecurityPermission(8, SkipVerification = true)]
