using System;

namespace System.Data.Common
{
	/// <summary>Provides the data for the RowUpdating event of a .NET Framework data provider.</summary>
	/// <filterpriority>2</filterpriority>
	// Token: 0x02000357 RID: 855
	public class RowUpdatingEventArgs : EventArgs
	{
		/// <summary>Initializes a new instance of the <see cref="T:System.Data.Common.RowUpdatingEventArgs" /> class.</summary>
		/// <param name="dataRow">The <see cref="T:System.Data.DataRow" /> to <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" />. </param>
		/// <param name="command">The <see cref="T:System.Data.IDbCommand" /> to execute when <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" /> is called. </param>
		/// <param name="statementType">The type of SQL statement to execute. </param>
		/// <param name="tableMapping">The <see cref="T:System.Data.Common.DataTableMapping" /> to send through an <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" />. </param>
		// Token: 0x0600296A RID: 10602 RVA: 0x000B501C File Offset: 0x000B321C
		public RowUpdatingEventArgs(DataRow dataRow, IDbCommand command, StatementType statementType, DataTableMapping tableMapping)
		{
			ADP.CheckArgumentNull(dataRow, "dataRow");
			ADP.CheckArgumentNull(tableMapping, "tableMapping");
			if (statementType <= StatementType.Delete)
			{
				this._dataRow = dataRow;
				this._command = command;
				this._statementType = statementType;
				this._tableMapping = tableMapping;
				return;
			}
			if (statementType == StatementType.Batch)
			{
				throw ADP.NotSupportedStatementType(statementType, "RowUpdatingEventArgs");
			}
			throw ADP.InvalidStatementType(statementType);
		}

		/// <summary>Gets or sets the <see cref="T:System.Data.IDbCommand" /> object for an instance of this class.</summary>
		/// <returns>The <see cref="T:System.Data.IDbCommand" /> to execute during the <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" />. </returns>
		// Token: 0x1700071B RID: 1819
		// (get) Token: 0x0600296B RID: 10603 RVA: 0x000B507E File Offset: 0x000B327E
		// (set) Token: 0x0600296C RID: 10604 RVA: 0x000B5086 File Offset: 0x000B3286
		protected virtual IDbCommand BaseCommand
		{
			get
			{
				return this._command;
			}
			set
			{
				this._command = value;
			}
		}

		/// <summary>Gets the <see cref="T:System.Data.IDbCommand" /> to execute during the <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" /> operation.</summary>
		/// <returns>The <see cref="T:System.Data.IDbCommand" /> to execute during the <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" />.</returns>
		/// <filterpriority>1</filterpriority>
		// Token: 0x1700071C RID: 1820
		// (get) Token: 0x0600296D RID: 10605 RVA: 0x000B508F File Offset: 0x000B328F
		// (set) Token: 0x0600296E RID: 10606 RVA: 0x000B5097 File Offset: 0x000B3297
		public IDbCommand Command
		{
			get
			{
				return this.BaseCommand;
			}
			set
			{
				this.BaseCommand = value;
			}
		}

		/// <summary>Gets any errors generated by the .NET Framework data provider when the <see cref="P:System.Data.Common.RowUpdatedEventArgs.Command" /> executes.</summary>
		/// <returns>The errors generated by the .NET Framework data provider when the <see cref="P:System.Data.Common.RowUpdatedEventArgs.Command" /> executes.</returns>
		/// <filterpriority>1</filterpriority>
		// Token: 0x1700071D RID: 1821
		// (get) Token: 0x0600296F RID: 10607 RVA: 0x000B50A0 File Offset: 0x000B32A0
		// (set) Token: 0x06002970 RID: 10608 RVA: 0x000B50A8 File Offset: 0x000B32A8
		public Exception Errors
		{
			get
			{
				return this._errors;
			}
			set
			{
				this._errors = value;
			}
		}

		/// <summary>Gets the <see cref="T:System.Data.DataRow" /> that will be sent to the server as part of an insert, update, or delete operation.</summary>
		/// <returns>The <see cref="T:System.Data.DataRow" /> to send through an <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" />.</returns>
		/// <filterpriority>1</filterpriority>
		// Token: 0x1700071E RID: 1822
		// (get) Token: 0x06002971 RID: 10609 RVA: 0x000B50B1 File Offset: 0x000B32B1
		public DataRow Row
		{
			get
			{
				return this._dataRow;
			}
		}

		/// <summary>Gets the type of SQL statement to execute.</summary>
		/// <returns>The type of SQL statement to execute.</returns>
		/// <filterpriority>1</filterpriority>
		// Token: 0x1700071F RID: 1823
		// (get) Token: 0x06002972 RID: 10610 RVA: 0x000B50B9 File Offset: 0x000B32B9
		public StatementType StatementType
		{
			get
			{
				return this._statementType;
			}
		}

		/// <summary>Gets or sets the <see cref="T:System.Data.UpdateStatus" /> of the <see cref="P:System.Data.Common.RowUpdatedEventArgs.Command" /> property.</summary>
		/// <returns>One of the <see cref="T:System.Data.UpdateStatus" /> values. The default is Continue.</returns>
		/// <filterpriority>1</filterpriority>
		/// <PermissionSet>
		///   <IPermission class="System.Security.Permissions.FileIOPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" PathDiscovery="*AllFiles*" />
		/// </PermissionSet>
		// Token: 0x17000720 RID: 1824
		// (get) Token: 0x06002973 RID: 10611 RVA: 0x000B50C1 File Offset: 0x000B32C1
		// (set) Token: 0x06002974 RID: 10612 RVA: 0x000B50C9 File Offset: 0x000B32C9
		public UpdateStatus Status
		{
			get
			{
				return this._status;
			}
			set
			{
				if (value <= UpdateStatus.SkipAllRemainingRows)
				{
					this._status = value;
					return;
				}
				throw ADP.InvalidUpdateStatus(value);
			}
		}

		/// <summary>Gets the <see cref="T:System.Data.Common.DataTableMapping" /> to send through the <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" />.</summary>
		/// <returns>The <see cref="T:System.Data.Common.DataTableMapping" /> to send through the <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" />.</returns>
		/// <filterpriority>1</filterpriority>
		// Token: 0x17000721 RID: 1825
		// (get) Token: 0x06002975 RID: 10613 RVA: 0x000B50DD File Offset: 0x000B32DD
		public DataTableMapping TableMapping
		{
			get
			{
				return this._tableMapping;
			}
		}

		// Token: 0x04001993 RID: 6547
		private IDbCommand _command;

		// Token: 0x04001994 RID: 6548
		private StatementType _statementType;

		// Token: 0x04001995 RID: 6549
		private DataTableMapping _tableMapping;

		// Token: 0x04001996 RID: 6550
		private Exception _errors;

		// Token: 0x04001997 RID: 6551
		private DataRow _dataRow;

		// Token: 0x04001998 RID: 6552
		private UpdateStatus _status;
	}
}
