using System;

namespace System.Data.Common
{
	/// <summary>Provides data for the RowUpdated event of a .NET Framework data provider.</summary>
	/// <filterpriority>2</filterpriority>
	// Token: 0x02000356 RID: 854
	public class RowUpdatedEventArgs : EventArgs
	{
		/// <summary>Initializes a new instance of the <see cref="T:System.Data.Common.RowUpdatedEventArgs" /> class.</summary>
		/// <param name="dataRow">The <see cref="T:System.Data.DataRow" /> sent through an <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" />. </param>
		/// <param name="command">The <see cref="T:System.Data.IDbCommand" /> executed when <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" /> is called. </param>
		/// <param name="statementType">The type of SQL statement executed. </param>
		/// <param name="tableMapping">The <see cref="T:System.Data.Common.DataTableMapping" /> sent through an <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" />. </param>
		// Token: 0x0600295A RID: 10586 RVA: 0x000B4EF8 File Offset: 0x000B30F8
		public RowUpdatedEventArgs(DataRow dataRow, IDbCommand command, StatementType statementType, DataTableMapping tableMapping)
		{
			if (statementType > StatementType.Batch)
			{
				throw ADP.InvalidStatementType(statementType);
			}
			this._dataRow = dataRow;
			this._command = command;
			this._statementType = statementType;
			this._tableMapping = tableMapping;
		}

		/// <summary>Gets the <see cref="T:System.Data.IDbCommand" /> executed when <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" /> is called.</summary>
		/// <returns>The <see cref="T:System.Data.IDbCommand" /> executed when <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" /> is called.</returns>
		/// <filterpriority>1</filterpriority>
		// Token: 0x17000712 RID: 1810
		// (get) Token: 0x0600295B RID: 10587 RVA: 0x000B4F28 File Offset: 0x000B3128
		public IDbCommand Command
		{
			get
			{
				return this._command;
			}
		}

		/// <summary>Gets any errors generated by the .NET Framework data provider when the <see cref="P:System.Data.Common.RowUpdatedEventArgs.Command" /> was executed.</summary>
		/// <returns>The errors generated by the .NET Framework data provider when the <see cref="P:System.Data.Common.RowUpdatedEventArgs.Command" /> was executed.</returns>
		/// <filterpriority>1</filterpriority>
		// Token: 0x17000713 RID: 1811
		// (get) Token: 0x0600295C RID: 10588 RVA: 0x000B4F30 File Offset: 0x000B3130
		// (set) Token: 0x0600295D RID: 10589 RVA: 0x000B4F38 File Offset: 0x000B3138
		public Exception Errors
		{
			get
			{
				return this._errors;
			}
			set
			{
				this._errors = value;
			}
		}

		/// <summary>Gets the number of rows changed, inserted, or deleted by execution of the SQL statement.</summary>
		/// <returns>The number of rows changed, inserted, or deleted; 0 if no rows were affected or the statement failed; and -1 for SELECT statements.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x17000714 RID: 1812
		// (get) Token: 0x0600295E RID: 10590 RVA: 0x000B4F41 File Offset: 0x000B3141
		public int RecordsAffected
		{
			get
			{
				return this._recordsAffected;
			}
		}

		/// <summary>Gets the <see cref="T:System.Data.DataRow" /> sent through an <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" />.</summary>
		/// <returns>The <see cref="T:System.Data.DataRow" /> sent through an <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" />.</returns>
		/// <filterpriority>1</filterpriority>
		// Token: 0x17000715 RID: 1813
		// (get) Token: 0x0600295F RID: 10591 RVA: 0x000B4F49 File Offset: 0x000B3149
		public DataRow Row
		{
			get
			{
				return this._dataRow;
			}
		}

		// Token: 0x17000716 RID: 1814
		// (get) Token: 0x06002960 RID: 10592 RVA: 0x000B4F51 File Offset: 0x000B3151
		internal DataRow[] Rows
		{
			get
			{
				return this._dataRows;
			}
		}

		/// <summary>Gets the number of rows processed in a batch of updated records.</summary>
		/// <returns>int that specifies the number of row processed.</returns>
		/// <filterpriority>1</filterpriority>
		// Token: 0x17000717 RID: 1815
		// (get) Token: 0x06002961 RID: 10593 RVA: 0x000B4F5C File Offset: 0x000B315C
		public int RowCount
		{
			get
			{
				DataRow[] dataRows = this._dataRows;
				if (dataRows != null)
				{
					return dataRows.Length;
				}
				if (this._dataRow == null)
				{
					return 0;
				}
				return 1;
			}
		}

		/// <summary>Gets the type of SQL statement executed.</summary>
		/// <returns>The type of SQL statement executed.</returns>
		/// <filterpriority>1</filterpriority>
		// Token: 0x17000718 RID: 1816
		// (get) Token: 0x06002962 RID: 10594 RVA: 0x000B4F82 File Offset: 0x000B3182
		public StatementType StatementType
		{
			get
			{
				return this._statementType;
			}
		}

		/// <summary>Gets the <see cref="T:System.Data.UpdateStatus" /> of the <see cref="P:System.Data.Common.RowUpdatedEventArgs.Command" /> property.</summary>
		/// <returns>One of the <see cref="T:System.Data.UpdateStatus" /> values. The default is Continue.</returns>
		/// <filterpriority>1</filterpriority>
		/// <PermissionSet>
		///   <IPermission class="System.Security.Permissions.FileIOPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" PathDiscovery="*AllFiles*" />
		/// </PermissionSet>
		// Token: 0x17000719 RID: 1817
		// (get) Token: 0x06002963 RID: 10595 RVA: 0x000B4F8A File Offset: 0x000B318A
		// (set) Token: 0x06002964 RID: 10596 RVA: 0x000B4F92 File Offset: 0x000B3192
		public UpdateStatus Status
		{
			get
			{
				return this._status;
			}
			set
			{
				if (value <= UpdateStatus.SkipAllRemainingRows)
				{
					this._status = value;
					return;
				}
				throw ADP.InvalidUpdateStatus(value);
			}
		}

		/// <summary>Gets the <see cref="T:System.Data.Common.DataTableMapping" /> sent through an <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" />.</summary>
		/// <returns>The <see cref="T:System.Data.Common.DataTableMapping" /> sent through an <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" />.</returns>
		/// <filterpriority>1</filterpriority>
		// Token: 0x1700071A RID: 1818
		// (get) Token: 0x06002965 RID: 10597 RVA: 0x000B4FA6 File Offset: 0x000B31A6
		public DataTableMapping TableMapping
		{
			get
			{
				return this._tableMapping;
			}
		}

		// Token: 0x06002966 RID: 10598 RVA: 0x000B4FAE File Offset: 0x000B31AE
		internal void AdapterInit(DataRow[] dataRows)
		{
			this._statementType = StatementType.Batch;
			this._dataRows = dataRows;
			if (dataRows != null && 1 == dataRows.Length)
			{
				this._dataRow = dataRows[0];
			}
		}

		// Token: 0x06002967 RID: 10599 RVA: 0x000B4FD0 File Offset: 0x000B31D0
		internal void AdapterInit(int recordsAffected)
		{
			this._recordsAffected = recordsAffected;
		}

		/// <summary>Copies references to the modified rows into the provided array.</summary>
		/// <param name="array">The array of <see cref="T:System.Data.DataRow" /> to copy into.</param>
		/// <filterpriority>2</filterpriority>
		/// <PermissionSet>
		///   <IPermission class="System.Security.Permissions.FileIOPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" PathDiscovery="*AllFiles*" />
		/// </PermissionSet>
		// Token: 0x06002968 RID: 10600 RVA: 0x000B4FD9 File Offset: 0x000B31D9
		public void CopyToRows(DataRow[] array)
		{
			this.CopyToRows(array, 0);
		}

		/// <summary>Copies references to the modified rows into the provided array. </summary>
		/// <param name="array">The array of <see cref="T:System.Data.DataRow" /> to copy into.</param>
		/// <param name="arrayIndex">The index in the array to start copying into.</param>
		/// <filterpriority>2</filterpriority>
		/// <PermissionSet>
		///   <IPermission class="System.Security.Permissions.FileIOPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" PathDiscovery="*AllFiles*" />
		/// </PermissionSet>
		// Token: 0x06002969 RID: 10601 RVA: 0x000B4FE4 File Offset: 0x000B31E4
		public void CopyToRows(DataRow[] array, int arrayIndex)
		{
			DataRow[] dataRows = this._dataRows;
			if (dataRows != null)
			{
				dataRows.CopyTo(array, arrayIndex);
				return;
			}
			if (array == null)
			{
				throw ADP.ArgumentNull("array");
			}
			array[arrayIndex] = this.Row;
		}

		// Token: 0x0400198B RID: 6539
		private IDbCommand _command;

		// Token: 0x0400198C RID: 6540
		private StatementType _statementType;

		// Token: 0x0400198D RID: 6541
		private DataTableMapping _tableMapping;

		// Token: 0x0400198E RID: 6542
		private Exception _errors;

		// Token: 0x0400198F RID: 6543
		private DataRow _dataRow;

		// Token: 0x04001990 RID: 6544
		private DataRow[] _dataRows;

		// Token: 0x04001991 RID: 6545
		private UpdateStatus _status;

		// Token: 0x04001992 RID: 6546
		private int _recordsAffected;
	}
}
