using System;
using System.Data.Common;
using System.Runtime.Serialization;
using System.Security.Permissions;

namespace System.Data.OleDb
{
	/// <summary>The exception that is thrown when the underlying provider returns a warning or error for an OLE DB data source. This class cannot be inherited.</summary>
	/// <filterpriority>2</filterpriority>
	// Token: 0x02000115 RID: 277
	[MonoTODO("OleDb is not implemented.")]
	public sealed class OleDbException : DbException
	{
		// Token: 0x06000F67 RID: 3943 RVA: 0x0004F1CA File Offset: 0x0004D3CA
		internal OleDbException()
		{
		}

		/// <summary>Gets the HRESULT of the error.</summary>
		/// <returns>The HRESULT of the error.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x17000299 RID: 665
		// (get) Token: 0x06000F68 RID: 3944 RVA: 0x0004EFE0 File Offset: 0x0004D1E0
		public override int ErrorCode
		{
			get
			{
				throw ADP.OleDb();
			}
		}

		/// <summary>Gets a collection of one or more <see cref="T:System.Data.OleDb.OleDbError" /> objects that give detailed information about exceptions generated by the .NET Framework Data Provider for OLE DB.</summary>
		/// <returns>The collected instances of the <see cref="T:System.Data.OleDb.OleDbError" /> class.</returns>
		/// <filterpriority>2</filterpriority>
		/// <PermissionSet>
		///   <IPermission class="System.Security.Permissions.SecurityPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Flags="UnmanagedCode, ControlEvidence" />
		/// </PermissionSet>
		// Token: 0x1700029A RID: 666
		// (get) Token: 0x06000F69 RID: 3945 RVA: 0x0004EFE0 File Offset: 0x0004D1E0
		public OleDbErrorCollection Errors
		{
			get
			{
				throw ADP.OleDb();
			}
		}

		/// <summary>This member overrides <see cref="M:System.Exception.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)" />.</summary>
		/// <param name="si">The <see cref="T:System.Runtime.Serialization.SerializationInfo" /> that holds the serialized object data about the exception being thrown.</param>
		/// <param name="context">The <see cref="T:System.Runtime.Serialization.StreamingContext" /> that contains contextual information about the source or destination.</param>
		/// <exception cref="T:System.ArgumentNullException">The <paramref name="si" /> parameter is a null reference (Nothing in Visual Basic).</exception>
		/// <filterpriority>2</filterpriority>
		/// <PermissionSet>
		///   <IPermission class="System.Security.Permissions.FileIOPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Unrestricted="true" />
		///   <IPermission class="System.Security.Permissions.SecurityPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Flags="ControlEvidence, SerializationFormatter" />
		/// </PermissionSet>
		// Token: 0x06000F6A RID: 3946 RVA: 0x0004EFE0 File Offset: 0x0004D1E0
		[SecurityPermission(SecurityAction.LinkDemand, Flags = SecurityPermissionFlag.SerializationFormatter)]
		public override void GetObjectData(SerializationInfo si, StreamingContext context)
		{
			throw ADP.OleDb();
		}
	}
}
