using System;
using System.Collections;
using System.Data.Common;

namespace System.Data.OleDb
{
	/// <summary>Collects all errors generated by the .NET Framework Data Provider for OLE DB. This class cannot be inherited.</summary>
	/// <filterpriority>2</filterpriority>
	// Token: 0x02000114 RID: 276
	[MonoTODO("OleDb is not implemented.")]
	public sealed class OleDbErrorCollection : ICollection, IEnumerable
	{
		// Token: 0x06000F5F RID: 3935 RVA: 0x00003D55 File Offset: 0x00001F55
		internal OleDbErrorCollection()
		{
		}

		/// <summary>Gets the number of errors in the collection.</summary>
		/// <returns>The total number of errors in the collection.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x17000295 RID: 661
		// (get) Token: 0x06000F60 RID: 3936 RVA: 0x0004EFE0 File Offset: 0x0004D1E0
		public int Count
		{
			get
			{
				throw ADP.OleDb();
			}
		}

		/// <summary>Copies the elements of the <see cref="T:System.Data.OleDb.OleDbErrorCollection" /> into an <see cref="T:System.Array" />, starting at the specified index within the <see cref="T:System.Array" />.</summary>
		/// <param name="array">The <see cref="T:System.Array" /> into which to copy the elements. </param>
		/// <param name="index">The starting index of the <paramref name="array" />. </param>
		/// <exception cref="T:System.ArgumentException">The sum of <paramref name="index" /> and the number of elements in the <see cref="T:System.Data.OleDb.OleDbErrorCollection" /> is greater than the length of the <see cref="T:System.Array" />. </exception>
		/// <exception cref="T:System.ArgumentNullException">The <paramref name="array" /> is null. </exception>
		/// <exception cref="T:System.ArgumentOutOfRangeException">The <paramref name="index" /> is not valid for <paramref name="array" />. </exception>
		/// <filterpriority>2</filterpriority>
		// Token: 0x06000F61 RID: 3937 RVA: 0x0004EFE0 File Offset: 0x0004D1E0
		public void CopyTo(Array array, int index)
		{
			throw ADP.OleDb();
		}

		/// <summary>Copies all the elements of the current <see cref="T:System.Data.OleDb.OleDbErrorCollection" /> to the specified <see cref="T:System.Data.OleDb.OleDbErrorCollection" /> starting at the specified destination index.</summary>
		/// <param name="array">The <see cref="T:System.Data.OleDb.OleDbErrorCollection" /> that is the destination of the elements copied from the current <see cref="T:System.Data.OleDb.OleDbErrorCollection" />. </param>
		/// <param name="index">A 32-bit integer that represents the index in the <see cref="T:System.Data.OleDb.OleDbErrorCollection" /> at which copying starts.</param>
		/// <filterpriority>2</filterpriority>
		// Token: 0x06000F62 RID: 3938 RVA: 0x0004EFE0 File Offset: 0x0004D1E0
		public void CopyTo(OleDbError[] array, int index)
		{
			throw ADP.OleDb();
		}

		/// <summary>Exposes the <see cref="M:System.Collections.IEnumerable.GetEnumerator" /> method, which supports a simple iteration over a collection by a .NET Framework data provider.</summary>
		/// <returns>An <see cref="T:System.Collections.IEnumerator" /> that can be used to iterate through the collection.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x06000F63 RID: 3939 RVA: 0x0004EFE0 File Offset: 0x0004D1E0
		public IEnumerator GetEnumerator()
		{
			throw ADP.OleDb();
		}

		/// <summary>Gets the error at the specified index.</summary>
		/// <returns>An <see cref="T:System.Data.OleDb.OleDbError" /> that contains the error at the specified index.</returns>
		/// <param name="index">The zero-based index of the error to retrieve. </param>
		/// <filterpriority>2</filterpriority>
		// Token: 0x17000296 RID: 662
		public OleDbError this[int index]
		{
			get
			{
				throw ADP.OleDb();
			}
		}

		/// <summary>For a description of this member, see <see cref="M:System.Collections.ICollection.IsSynchronized" />.</summary>
		/// <returns>true if access to the collection is synchronized (thread safe); otherwise, false. The default is false.</returns>
		// Token: 0x17000297 RID: 663
		// (get) Token: 0x06000F65 RID: 3941 RVA: 0x0004EFE0 File Offset: 0x0004D1E0
		bool ICollection.IsSynchronized
		{
			get
			{
				throw ADP.OleDb();
			}
		}

		/// <summary>For a description of this member, see <see cref="M:System.Collections.ICollection.SyncRoot" />.</summary>
		/// <returns>A <see cref="T:System.Object" /> that can be used to synchronize access to the collection.</returns>
		// Token: 0x17000298 RID: 664
		// (get) Token: 0x06000F66 RID: 3942 RVA: 0x0004EFE0 File Offset: 0x0004D1E0
		object ICollection.SyncRoot
		{
			get
			{
				throw ADP.OleDb();
			}
		}
	}
}
