using System;
using Unity;

namespace System.Data.SqlClient
{
	/// <summary>Collects information relevant to a warning or error returned by SQL Server.</summary>
	/// <filterpriority>1</filterpriority>
	// Token: 0x020001AF RID: 431
	[Serializable]
	public sealed class SqlError
	{
		// Token: 0x060014D8 RID: 5336 RVA: 0x00068274 File Offset: 0x00066474
		internal SqlError(int infoNumber, byte errorState, byte errorClass, string server, string errorMessage, string procedure, int lineNumber, uint win32ErrorCode, Exception exception = null)
			: this(infoNumber, errorState, errorClass, server, errorMessage, procedure, lineNumber, exception)
		{
			this._win32ErrorCode = (int)win32ErrorCode;
		}

		// Token: 0x060014D9 RID: 5337 RVA: 0x0006829C File Offset: 0x0006649C
		internal SqlError(int infoNumber, byte errorState, byte errorClass, string server, string errorMessage, string procedure, int lineNumber, Exception exception = null)
		{
			this._source = "Core .Net SqlClient Data Provider";
			base..ctor();
			this._number = infoNumber;
			this._state = errorState;
			this._errorClass = errorClass;
			this._server = server;
			this._message = errorMessage;
			this._procedure = procedure;
			this._lineNumber = lineNumber;
			this._win32ErrorCode = 0;
			this._exception = exception;
		}

		/// <summary>Gets the complete text of the error message.</summary>
		/// <returns>The complete text of the error.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x060014DA RID: 5338 RVA: 0x000682FE File Offset: 0x000664FE
		public override string ToString()
		{
			return typeof(SqlError).ToString() + ": " + this._message;
		}

		/// <summary>Gets the name of the provider that generated the error.</summary>
		/// <returns>The name of the provider that generated the error.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x170003CD RID: 973
		// (get) Token: 0x060014DB RID: 5339 RVA: 0x0006831F File Offset: 0x0006651F
		public string Source
		{
			get
			{
				return this._source;
			}
		}

		/// <summary>Gets a number that identifies the type of error.</summary>
		/// <returns>The number that identifies the type of error.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x170003CE RID: 974
		// (get) Token: 0x060014DC RID: 5340 RVA: 0x00068327 File Offset: 0x00066527
		public int Number
		{
			get
			{
				return this._number;
			}
		}

		/// <summary>Some error messages can be raised at multiple points in the code for the Database Engine. For example, an 1105 error can be raised for several different conditions. Each specific condition that raises an error assigns a unique state code.</summary>
		/// <returns>The state code.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x170003CF RID: 975
		// (get) Token: 0x060014DD RID: 5341 RVA: 0x0006832F File Offset: 0x0006652F
		public byte State
		{
			get
			{
				return this._state;
			}
		}

		/// <summary>Gets the severity level of the error returned from SQL Server.</summary>
		/// <returns>A value from 1 to 25 that indicates the severity level of the error. The default is 0.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x170003D0 RID: 976
		// (get) Token: 0x060014DE RID: 5342 RVA: 0x00068337 File Offset: 0x00066537
		public byte Class
		{
			get
			{
				return this._errorClass;
			}
		}

		/// <summary>Gets the name of the instance of SQL Server that generated the error.</summary>
		/// <returns>The name of the instance of SQL Server.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x170003D1 RID: 977
		// (get) Token: 0x060014DF RID: 5343 RVA: 0x0006833F File Offset: 0x0006653F
		public string Server
		{
			get
			{
				return this._server;
			}
		}

		/// <summary>Gets the text describing the error.</summary>
		/// <returns>The text describing the error.For more information on errors generated by SQL Server, see SQL Server Books Online.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x170003D2 RID: 978
		// (get) Token: 0x060014E0 RID: 5344 RVA: 0x00068347 File Offset: 0x00066547
		public string Message
		{
			get
			{
				return this._message;
			}
		}

		/// <summary>Gets the name of the stored procedure or remote procedure call (RPC) that generated the error.</summary>
		/// <returns>The name of the stored procedure or RPC.For more information on errors generated by SQL Server, see SQL Server Books Online.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x170003D3 RID: 979
		// (get) Token: 0x060014E1 RID: 5345 RVA: 0x0006834F File Offset: 0x0006654F
		public string Procedure
		{
			get
			{
				return this._procedure;
			}
		}

		/// <summary>Gets the line number within the Transact-SQL command batch or stored procedure that contains the error.</summary>
		/// <returns>The line number within the Transact-SQL command batch or stored procedure that contains the error.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x170003D4 RID: 980
		// (get) Token: 0x060014E2 RID: 5346 RVA: 0x00068357 File Offset: 0x00066557
		public int LineNumber
		{
			get
			{
				return this._lineNumber;
			}
		}

		// Token: 0x170003D5 RID: 981
		// (get) Token: 0x060014E3 RID: 5347 RVA: 0x0006835F File Offset: 0x0006655F
		internal int Win32ErrorCode
		{
			get
			{
				return this._win32ErrorCode;
			}
		}

		// Token: 0x170003D6 RID: 982
		// (get) Token: 0x060014E4 RID: 5348 RVA: 0x00068367 File Offset: 0x00066567
		internal Exception Exception
		{
			get
			{
				return this._exception;
			}
		}

		// Token: 0x060014E5 RID: 5349 RVA: 0x0000E24C File Offset: 0x0000C44C
		internal SqlError()
		{
			global::Unity.ThrowStub.ThrowNotSupportedException();
		}

		// Token: 0x04000E1B RID: 3611
		private string _source;

		// Token: 0x04000E1C RID: 3612
		private int _number;

		// Token: 0x04000E1D RID: 3613
		private byte _state;

		// Token: 0x04000E1E RID: 3614
		private byte _errorClass;

		// Token: 0x04000E1F RID: 3615
		private string _server;

		// Token: 0x04000E20 RID: 3616
		private string _message;

		// Token: 0x04000E21 RID: 3617
		private string _procedure;

		// Token: 0x04000E22 RID: 3618
		private int _lineNumber;

		// Token: 0x04000E23 RID: 3619
		private int _win32ErrorCode;

		// Token: 0x04000E24 RID: 3620
		private Exception _exception;
	}
}
