using System;
using System.Collections;
using System.Collections.Generic;

namespace System.Data.SqlClient
{
	/// <summary>Collects all errors generated by the .NET Framework Data Provider for SQL Server. This class cannot be inherited. </summary>
	/// <filterpriority>1</filterpriority>
	// Token: 0x020001B0 RID: 432
	[Serializable]
	public sealed class SqlErrorCollection : ICollection, IEnumerable
	{
		// Token: 0x060014E6 RID: 5350 RVA: 0x0006836F File Offset: 0x0006656F
		internal SqlErrorCollection()
		{
		}

		/// <summary>Copies the elements of the <see cref="T:System.Data.SqlClient.SqlErrorCollection" /> collection into an <see cref="T:System.Array" />, starting at the specified index.</summary>
		/// <param name="array">The <see cref="T:System.Array" /> to copy elements into. </param>
		/// <param name="index">The index from which to start copying into the <paramref name="array" /> parameter. </param>
		/// <exception cref="T:System.ArgumentException">The sum of <paramref name="index" /> and the number of elements in the <see cref="T:System.Data.SqlClient.SqlErrorCollection" /> collection is greater than the <see cref="P:System.Array.Length" /> of the <see cref="T:System.Array" />. </exception>
		/// <exception cref="T:System.ArgumentNullException">The <paramref name="array" /> is null. </exception>
		/// <exception cref="T:System.ArgumentOutOfRangeException">The <paramref name="index" /> is not valid for <paramref name="array" />. </exception>
		/// <filterpriority>2</filterpriority>
		// Token: 0x060014E7 RID: 5351 RVA: 0x00068382 File Offset: 0x00066582
		public void CopyTo(Array array, int index)
		{
			((ICollection)this._errors).CopyTo(array, index);
		}

		/// <summary>Copies the elements of the <see cref="T:System.Data.SqlClient.SqlErrorCollection" /> collection into a <see cref="T:System.Data.SqlClient.SqlErrorCollection" />, starting at the specified index.</summary>
		/// <param name="array">The <see cref="T:System.Data.SqlClient.SqlErrorCollection" /> to copy the elements into.</param>
		/// <param name="index">The index from which to start copying into the <paramref name="array" /> parameter.</param>
		/// <exception cref="T:System.ArgumentException">The sum of <paramref name="index" /> and the number of elements in the <see cref="T:System.Data.SqlClient.SqlErrorCollection" /> collection is greater than the length of the <see cref="T:System.Data.SqlClient.SqlErrorCollection" />. </exception>
		/// <exception cref="T:System.ArgumentNullException">The <paramref name="array" /> is null. </exception>
		/// <exception cref="T:System.ArgumentOutOfRangeException">The <paramref name="index" /> is not valid for <paramref name="array" />. </exception>
		/// <filterpriority>2</filterpriority>
		// Token: 0x060014E8 RID: 5352 RVA: 0x00068394 File Offset: 0x00066594
		public void CopyTo(SqlError[] array, int index)
		{
			this._errors.CopyTo(array, index);
		}

		/// <summary>Gets the number of errors in the collection.</summary>
		/// <returns>The total number of errors in the collection.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x170003D7 RID: 983
		// (get) Token: 0x060014E9 RID: 5353 RVA: 0x000683B0 File Offset: 0x000665B0
		public int Count
		{
			get
			{
				return this._errors.Count;
			}
		}

		/// <summary>For a description of this member, see <see cref="P:System.Collections.ICollection.SyncRoot" />.</summary>
		/// <returns>An object that can be used to synchronize access to the <see cref="T:System.Collections.ICollection" />.</returns>
		// Token: 0x170003D8 RID: 984
		// (get) Token: 0x060014EA RID: 5354 RVA: 0x0000565A File Offset: 0x0000385A
		object ICollection.SyncRoot
		{
			get
			{
				return this;
			}
		}

		/// <summary>For a description of this member, see <see cref="P:System.Collections.ICollection.IsSynchronized" />.</summary>
		/// <returns>true if access to the <see cref="T:System.Collections.ICollection" /> is synchronized (thread safe); otherwise, false.</returns>
		// Token: 0x170003D9 RID: 985
		// (get) Token: 0x060014EB RID: 5355 RVA: 0x00005AE9 File Offset: 0x00003CE9
		bool ICollection.IsSynchronized
		{
			get
			{
				return false;
			}
		}

		/// <summary>Gets the error at the specified index.</summary>
		/// <returns>A <see cref="T:System.Data.SqlClient.SqlError" /> that contains the error at the specified index.</returns>
		/// <param name="index">The zero-based index of the error to retrieve. </param>
		/// <exception cref="T:System.IndexOutOfRangeException">Index parameter is outside array bounds. </exception>
		/// <filterpriority>2</filterpriority>
		// Token: 0x170003DA RID: 986
		public SqlError this[int index]
		{
			get
			{
				return (SqlError)this._errors[index];
			}
		}

		/// <summary>Returns an enumerator that iterates through the <see cref="T:System.Data.SqlClient.SqlErrorCollection" />.</summary>
		/// <returns>An <see cref="T:System.Collections.IEnumerator" /> for the <see cref="T:System.Data.SqlClient.SqlErrorCollection" />.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x060014ED RID: 5357 RVA: 0x000683D0 File Offset: 0x000665D0
		public IEnumerator GetEnumerator()
		{
			return this._errors.GetEnumerator();
		}

		// Token: 0x060014EE RID: 5358 RVA: 0x000683E2 File Offset: 0x000665E2
		internal void Add(SqlError error)
		{
			this._errors.Add(error);
		}

		// Token: 0x04000E25 RID: 3621
		private readonly List<object> _errors = new List<object>();
	}
}
