using System;
using System.Collections;
using System.ComponentModel;
using System.Data.Common;
using System.Globalization;
using System.Runtime.Serialization;
using System.Security.Permissions;
using System.Text;
using Unity;

namespace System.Data.SqlClient
{
	/// <summary>The exception that is thrown when SQL Server returns a warning or error. This class cannot be inherited.</summary>
	/// <filterpriority>1</filterpriority>
	// Token: 0x020001B1 RID: 433
	[Serializable]
	public sealed class SqlException : DbException
	{
		// Token: 0x060014EF RID: 5359 RVA: 0x000683F0 File Offset: 0x000665F0
		private SqlException(string message, SqlErrorCollection errorCollection, Exception innerException, Guid conId)
		{
			this._clientConnectionId = Guid.Empty;
			base..ctor(message, innerException);
			base.HResult = -2146232060;
			this._errors = errorCollection;
			this._clientConnectionId = conId;
		}

		// Token: 0x060014F0 RID: 5360 RVA: 0x00068420 File Offset: 0x00066620
		private SqlException(SerializationInfo si, StreamingContext sc)
		{
			this._clientConnectionId = Guid.Empty;
			base..ctor(si, sc);
			base.HResult = -2146232060;
			foreach (SerializationEntry serializationEntry in si)
			{
				if ("ClientConnectionId" == serializationEntry.Name)
				{
					this._clientConnectionId = (Guid)serializationEntry.Value;
					return;
				}
			}
		}

		/// <summary>Sets the <see cref="T:System.Runtime.Serialization.SerializationInfo" /> with information about the exception.</summary>
		/// <param name="si">The <see cref="T:System.Runtime.Serialization.SerializationInfo" /> that holds the serialized object data about the exception being thrown. </param>
		/// <param name="context">The <see cref="T:System.Runtime.Serialization.StreamingContext" /> that contains contextual information about the source or destination.</param>
		/// <exception cref="T:System.ArgumentNullException">The <paramref name="si" /> parameter is a null reference (Nothing in Visual Basic).</exception>
		/// <filterpriority>2</filterpriority>
		/// <PermissionSet>
		///   <IPermission class="System.Security.Permissions.FileIOPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Unrestricted="true" />
		///   <IPermission class="System.Security.Permissions.SecurityPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Flags="ControlEvidence, SerializationFormatter" />
		/// </PermissionSet>
		// Token: 0x060014F1 RID: 5361 RVA: 0x0006848C File Offset: 0x0006668C
		[SecurityPermission(SecurityAction.LinkDemand, Flags = SecurityPermissionFlag.SerializationFormatter)]
		public override void GetObjectData(SerializationInfo si, StreamingContext context)
		{
			base.GetObjectData(si, context);
			si.AddValue("Errors", null);
			si.AddValue("ClientConnectionId", this._clientConnectionId, typeof(Guid));
			for (int i = 0; i < this.Errors.Count; i++)
			{
				string text = "SqlError " + (i + 1).ToString();
				if (this.Data.Contains(text))
				{
					this.Data.Remove(text);
				}
				this.Data.Add(text, this.Errors[i].ToString());
			}
		}

		/// <summary>Gets a collection of one or more <see cref="T:System.Data.SqlClient.SqlError" /> objects that give detailed information about exceptions generated by the .NET Framework Data Provider for SQL Server.</summary>
		/// <returns>The collected instances of the <see cref="T:System.Data.SqlClient.SqlError" /> class.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x170003DB RID: 987
		// (get) Token: 0x060014F2 RID: 5362 RVA: 0x00068530 File Offset: 0x00066730
		public SqlErrorCollection Errors
		{
			get
			{
				if (this._errors == null)
				{
					this._errors = new SqlErrorCollection();
				}
				return this._errors;
			}
		}

		/// <summary>Represents the client connection ID. For more information, see Data Tracing in ADO.NET.</summary>
		/// <returns>Returns the client connection ID.</returns>
		// Token: 0x170003DC RID: 988
		// (get) Token: 0x060014F3 RID: 5363 RVA: 0x0006854B File Offset: 0x0006674B
		public Guid ClientConnectionId
		{
			get
			{
				return this._clientConnectionId;
			}
		}

		/// <summary>Gets the severity level of the error returned from the .NET Framework Data Provider for SQL Server.</summary>
		/// <returns>A value from 1 to 25 that indicates the severity level of the error.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x170003DD RID: 989
		// (get) Token: 0x060014F4 RID: 5364 RVA: 0x00068553 File Offset: 0x00066753
		public byte Class
		{
			get
			{
				if (this.Errors.Count <= 0)
				{
					return 0;
				}
				return this.Errors[0].Class;
			}
		}

		/// <summary>Gets the line number within the Transact-SQL command batch or stored procedure that generated the error.</summary>
		/// <returns>The line number within the Transact-SQL command batch or stored procedure that generated the error.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x170003DE RID: 990
		// (get) Token: 0x060014F5 RID: 5365 RVA: 0x00068576 File Offset: 0x00066776
		public int LineNumber
		{
			get
			{
				if (this.Errors.Count <= 0)
				{
					return 0;
				}
				return this.Errors[0].LineNumber;
			}
		}

		/// <summary>Gets a number that identifies the type of error.</summary>
		/// <returns>The number that identifies the type of error.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x170003DF RID: 991
		// (get) Token: 0x060014F6 RID: 5366 RVA: 0x00068599 File Offset: 0x00066799
		public int Number
		{
			get
			{
				if (this.Errors.Count <= 0)
				{
					return 0;
				}
				return this.Errors[0].Number;
			}
		}

		/// <summary>Gets the name of the stored procedure or remote procedure call (RPC) that generated the error.</summary>
		/// <returns>The name of the stored procedure or RPC.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x170003E0 RID: 992
		// (get) Token: 0x060014F7 RID: 5367 RVA: 0x000685BC File Offset: 0x000667BC
		public string Procedure
		{
			get
			{
				if (this.Errors.Count <= 0)
				{
					return null;
				}
				return this.Errors[0].Procedure;
			}
		}

		/// <summary>Gets the name of the computer that is running an instance of SQL Server that generated the error.</summary>
		/// <returns>The name of the computer running an instance of SQL Server.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x170003E1 RID: 993
		// (get) Token: 0x060014F8 RID: 5368 RVA: 0x000685DF File Offset: 0x000667DF
		public string Server
		{
			get
			{
				if (this.Errors.Count <= 0)
				{
					return null;
				}
				return this.Errors[0].Server;
			}
		}

		/// <summary>Gets a numeric error code from SQL Server that represents an error, warning or "no data found" message. For more information about how to decode these values, see SQL Server Books Online.</summary>
		/// <returns>The number representing the error code.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x170003E2 RID: 994
		// (get) Token: 0x060014F9 RID: 5369 RVA: 0x00068602 File Offset: 0x00066802
		public byte State
		{
			get
			{
				if (this.Errors.Count <= 0)
				{
					return 0;
				}
				return this.Errors[0].State;
			}
		}

		/// <summary>Gets the name of the provider that generated the error.</summary>
		/// <returns>The name of the provider that generated the error.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x170003E3 RID: 995
		// (get) Token: 0x060014FA RID: 5370 RVA: 0x00068625 File Offset: 0x00066825
		public override string Source
		{
			get
			{
				if (this.Errors.Count <= 0)
				{
					return null;
				}
				return this.Errors[0].Source;
			}
		}

		/// <summary>Returns a string that represents the current <see cref="T:System.Data.SqlClient.SqlException" /> object, and includes the client connection ID (for more information, see <see cref="P:System.Data.SqlClient.SqlException.ClientConnectionId" />).</summary>
		/// <returns>A string that represents the current <see cref="T:System.Data.SqlClient.SqlException" /> object.<see cref="T:System.String" />.</returns>
		// Token: 0x060014FB RID: 5371 RVA: 0x00068648 File Offset: 0x00066848
		public override string ToString()
		{
			StringBuilder stringBuilder = new StringBuilder(base.ToString());
			stringBuilder.AppendLine();
			stringBuilder.AppendFormat(SQLMessage.ExClientConnectionId(), this._clientConnectionId);
			if (this.Errors.Count > 0 && this.Number != 0)
			{
				stringBuilder.AppendLine();
				stringBuilder.AppendFormat(SQLMessage.ExErrorNumberStateClass(), this.Number, this.State, this.Class);
			}
			if (this.Data.Contains("OriginalClientConnectionId"))
			{
				stringBuilder.AppendLine();
				stringBuilder.AppendFormat(SQLMessage.ExOriginalClientConnectionId(), this.Data["OriginalClientConnectionId"]);
			}
			if (this.Data.Contains("RoutingDestination"))
			{
				stringBuilder.AppendLine();
				stringBuilder.AppendFormat(SQLMessage.ExRoutingDestination(), this.Data["RoutingDestination"]);
			}
			return stringBuilder.ToString();
		}

		// Token: 0x060014FC RID: 5372 RVA: 0x00068739 File Offset: 0x00066939
		internal static SqlException CreateException(SqlErrorCollection errorCollection, string serverVersion)
		{
			return SqlException.CreateException(errorCollection, serverVersion, Guid.Empty, null);
		}

		// Token: 0x060014FD RID: 5373 RVA: 0x00068748 File Offset: 0x00066948
		internal static SqlException CreateException(SqlErrorCollection errorCollection, string serverVersion, SqlInternalConnectionTds internalConnection, Exception innerException = null)
		{
			Guid guid = ((internalConnection == null) ? Guid.Empty : internalConnection._clientConnectionId);
			SqlException ex = SqlException.CreateException(errorCollection, serverVersion, guid, innerException);
			if (internalConnection != null)
			{
				if (internalConnection.OriginalClientConnectionId != Guid.Empty && internalConnection.OriginalClientConnectionId != internalConnection.ClientConnectionId)
				{
					ex.Data.Add("OriginalClientConnectionId", internalConnection.OriginalClientConnectionId);
				}
				if (!string.IsNullOrEmpty(internalConnection.RoutingDestination))
				{
					ex.Data.Add("RoutingDestination", internalConnection.RoutingDestination);
				}
			}
			return ex;
		}

		// Token: 0x060014FE RID: 5374 RVA: 0x000687D8 File Offset: 0x000669D8
		internal static SqlException CreateException(SqlErrorCollection errorCollection, string serverVersion, Guid conId, Exception innerException = null)
		{
			StringBuilder stringBuilder = new StringBuilder();
			for (int i = 0; i < errorCollection.Count; i++)
			{
				if (i > 0)
				{
					stringBuilder.Append(Environment.NewLine);
				}
				stringBuilder.Append(errorCollection[i].Message);
			}
			if (innerException == null && errorCollection[0].Win32ErrorCode != 0 && errorCollection[0].Win32ErrorCode != -1)
			{
				innerException = new Win32Exception(errorCollection[0].Win32ErrorCode);
			}
			SqlException ex = new SqlException(stringBuilder.ToString(), errorCollection, innerException, conId);
			ex.Data.Add("HelpLink.ProdName", "Microsoft SQL Server");
			if (!string.IsNullOrEmpty(serverVersion))
			{
				ex.Data.Add("HelpLink.ProdVer", serverVersion);
			}
			ex.Data.Add("HelpLink.EvtSrc", "MSSQLServer");
			ex.Data.Add("HelpLink.EvtID", errorCollection[0].Number.ToString(CultureInfo.InvariantCulture));
			ex.Data.Add("HelpLink.BaseHelpUrl", "http://go.microsoft.com/fwlink");
			ex.Data.Add("HelpLink.LinkId", "20476");
			return ex;
		}

		// Token: 0x060014FF RID: 5375 RVA: 0x000688F8 File Offset: 0x00066AF8
		internal SqlException InternalClone()
		{
			SqlException ex = new SqlException(this.Message, this._errors, base.InnerException, this._clientConnectionId);
			if (this.Data != null)
			{
				foreach (object obj in this.Data)
				{
					DictionaryEntry dictionaryEntry = (DictionaryEntry)obj;
					ex.Data.Add(dictionaryEntry.Key, dictionaryEntry.Value);
				}
			}
			ex._doNotReconnect = this._doNotReconnect;
			return ex;
		}

		// Token: 0x170003E4 RID: 996
		// (get) Token: 0x06001500 RID: 5376 RVA: 0x00068998 File Offset: 0x00066B98
		public override string Message
		{
			get
			{
				if (this.Errors.Count == 0)
				{
					return base.Message;
				}
				StringBuilder stringBuilder = new StringBuilder();
				if (base.Message != "SQL Exception has occured.")
				{
					stringBuilder.Append(base.Message);
					stringBuilder.Append("\n");
				}
				for (int i = 0; i < this.Errors.Count - 1; i++)
				{
					stringBuilder.Append(this.Errors[i].Message);
					stringBuilder.Append("\n");
				}
				stringBuilder.Append(this.Errors[this.Errors.Count - 1].Message);
				return stringBuilder.ToString();
			}
		}

		// Token: 0x06001501 RID: 5377 RVA: 0x0000E24C File Offset: 0x0000C44C
		internal SqlException()
		{
			global::Unity.ThrowStub.ThrowNotSupportedException();
		}

		// Token: 0x04000E26 RID: 3622
		private const string OriginalClientConnectionIdKey = "OriginalClientConnectionId";

		// Token: 0x04000E27 RID: 3623
		private const string RoutingDestinationKey = "RoutingDestination";

		// Token: 0x04000E28 RID: 3624
		private const int SqlExceptionHResult = -2146232060;

		// Token: 0x04000E29 RID: 3625
		private SqlErrorCollection _errors;

		// Token: 0x04000E2A RID: 3626
		private Guid _clientConnectionId;

		// Token: 0x04000E2B RID: 3627
		internal bool _doNotReconnect;

		// Token: 0x04000E2C RID: 3628
		private const string DEF_MESSAGE = "SQL Exception has occured.";
	}
}
