using System;

namespace System.Data.SqlClient
{
	/// <summary>Represents the set of arguments passed to the notification event handler.</summary>
	/// <filterpriority>2</filterpriority>
	// Token: 0x020001C1 RID: 449
	public class SqlNotificationEventArgs : EventArgs
	{
		/// <summary>Creates a new instance of the <see cref="T:System.Data.SqlClient.SqlNotificationEventArgs" /> object. </summary>
		/// <param name="type">
		///   <see cref="T:System.Data.SqlClient.SqlNotificationType" /> value that indicates whether this notification is generated because of an actual change, or by the subscription. </param>
		/// <param name="info">
		///   <see cref="T:System.Data.SqlClient.SqlNotificationInfo" /> value that indicates the reason for the notification event. This may occur because the data in the store actually changed, or the notification became invalid (for example, it timed out). </param>
		/// <param name="source">
		///   <see cref="T:System.Data.SqlClient.SqlNotificationSource" /> value that indicates the source that generated the notification. </param>
		// Token: 0x060015BF RID: 5567 RVA: 0x0006B6C9 File Offset: 0x000698C9
		public SqlNotificationEventArgs(SqlNotificationType type, SqlNotificationInfo info, SqlNotificationSource source)
		{
			this._info = info;
			this._source = source;
			this._type = type;
		}

		/// <summary>Gets a value that indicates whether this notification is generated because of an actual change, or by the subscription.</summary>
		/// <returns>A value indicating whether the notification was generated by a change or a subscription.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x17000425 RID: 1061
		// (get) Token: 0x060015C0 RID: 5568 RVA: 0x0006B6E6 File Offset: 0x000698E6
		public SqlNotificationType Type
		{
			get
			{
				return this._type;
			}
		}

		/// <summary>Gets a value that indicates the reason for the notification event, such as a row in the database being modified or a table being truncated.</summary>
		/// <returns>The notification event reason.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x17000426 RID: 1062
		// (get) Token: 0x060015C1 RID: 5569 RVA: 0x0006B6EE File Offset: 0x000698EE
		public SqlNotificationInfo Info
		{
			get
			{
				return this._info;
			}
		}

		/// <summary>Gets a value that indicates the source that generated the notification, such as a change to the query data or the database’s state.</summary>
		/// <returns>The source of the notification.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x17000427 RID: 1063
		// (get) Token: 0x060015C2 RID: 5570 RVA: 0x0006B6F6 File Offset: 0x000698F6
		public SqlNotificationSource Source
		{
			get
			{
				return this._source;
			}
		}

		// Token: 0x04000E95 RID: 3733
		private SqlNotificationType _type;

		// Token: 0x04000E96 RID: 3734
		private SqlNotificationInfo _info;

		// Token: 0x04000E97 RID: 3735
		private SqlNotificationSource _source;

		// Token: 0x04000E98 RID: 3736
		internal static SqlNotificationEventArgs s_notifyError = new SqlNotificationEventArgs(SqlNotificationType.Subscribe, SqlNotificationInfo.Error, SqlNotificationSource.Object);
	}
}
